import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quickli Code Challenge Stub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Quickli </span> Code
            Challenge <span className="text-xl text-gray-400">(Stub)</span>
          </h1>
          <div className="mx-auto max-w-2xl space-y-6">
            <div className="rounded-lg border border-purple-800 bg-purple-900/30 p-6">
              <p className="text-lg text-white/80">
                Before starting the challenge, familiarize yourself with the
                application structure and complete a test deployment. This
                preparation will ensure you can dive straight into coding /
                solutioning when the challenge clock begins.
              </p>
            </div>
            <div className="rounded-lg border border-purple-800 bg-purple-900/30 p-6">
              <p className="text-lg text-white/80">
                Clone the repository, review the documentation, and deploy to
                Vercel. Understanding the development workflow now will help you
                focus on the challenge later.
              </p>
            </div>
          </div>
          <h2 className="text-4xl font-extrabold tracking-tight text-white">
            👇 <span className="text-[hsl(280,100%,70%)]">T3 </span> provided
            snacks 👇
          </h2>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.email}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
      {sessionData && (
        <Link
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          href="/scenario"
        >
          Check out the scenarios page
        </Link>
      )}
    </div>
  );
}
